database:
  host:
  user:
  password:
  port:
  name:
  sslmode:

app:
  name:
  http:
    port:

redis:
  address: 
  port: 
  client_name: 
  password: 

server:
  cors:
    allow_origins:
    allow_methods:
    allow_headers:
    expose_headers:
    max_age:
    allow_credential:

jwt:
  secret_key:
