database:
  host: "localhost"
  user: "user_test"
  password: "password_test"
  port: "5433"
  name: "testdb"
  sslmode: "disable"

app:
  name: "test_app_name"
  url: "http://localhost:8181"
  http:
    port: 8181
  grpc:
    service:
      user_service: 127.0.0.1:50051
      file_service: 127.0.0.1:50052
  verification_url: "verify-email?"
  changepassword_url: "change-password?"

redis:
  address: "localhost"
  port: "6379"
  client_name: "auth_service_test"
  password: "password_test"

minio:
  host: "localhost"
  port: 9000
  credential:
    user: "user_test"
    password: "password_test"

nats:
  protocol: "nats"
  address: "localhost"
  port: "4221"
  credential:
    user: "user_test"
    password: "password_test"
  connection_name: "authentication_service_conn_test"
  timeout: 10

jetstream:
  notification:
    stream: 
      name: "notification_stream_test"
      description: "this is notification stream"
    subject:
      global: "test_notif.>"
      mail: "test_notif.email"
  event:
    stream: 
      name: "event_stream_test"
      description: "this is event bus stream"
    consumer:
      user_event:
        name: "test_auth-user_consumer"
        subject: "test_event.user.*"
    subject:
      global: "test_event.>"
      event_bus: "test_event"
server:
  cors:
    allow_origins: "*"
    allow_methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    allow_headers: "Content-Type, Authorization, X-Requested-With, X-CSRF-Token, Accept, Origin, Cache-Control, X-File-Name, X-File-Type, X-File-Size"
    expose_headers: "Content-Length, Content-Range"
    max_age: 86400
    allow_credential: true

jwt:
  secret_key: "jwt_secret_test"

container:
  file_service_version: "v0.0.1"
  user_service_version: "v0.0.1"
  notification_service_version: "v0.0.1"
  nats_version: "2.11.6"
  minio_version: "RELEASE.2025-05-24T17-08-30Z-cpuv1"
  mailhog_version: "v1.0.1"
  postgresql_version: "17.5-alpine3.22"
  redis_version : "7.2"